language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master

env:
  - LOGS_DIR=/tmp/keen-build/logs

install:
  - npm install
  - gulp test:unit

before_script:
  - mkdir -p $LOGS_DIR

notifications:
  email:
    on_success: never